package com.example.entity;

public enum UserState {
    DEFAULT,
    AWAITING_PHONE,
    ADD_POINTS_AWAITING_PHONE,
    ADD_POINTS_AWAITING_AMOUNT,
    REDEEM_AWAITING_PHONE,
    REDEEM_AWAITING_AMOUNT,
    ADD_EMPLOYEE_AWAITING_PHONE
}